### ISSUE TITLE
Add feature to upload the files to Commons

### ISSUE THREAD

**Issue by bodhisattwawiki** [abartov/pronuncify#1]
It would be great to add a feature to this tool, so that the recorded words can be mass uploaded to Commons.

**Comment by abartov** [comment]
Indeed, I was planning to do this at some point.  Ideally it would be with OAuth and not require the user's credentials, but that seemed too much of a hassle for a command-line tool, so for now, I have implemented uploading (including categorization and moving of files to an /uploaded subdirectory) with explicit credentials.  Get the latest code and see the updated README.md for instructions.  Let me know if you run into any difficulty! :)
