### ISSUE TITLE
Add summary and license to the files

### ISSUE THREAD

**Issue by bodhisattwawiki** [abartov/pronuncify#3]
The Summary section (Description, Author, Date, Source etc.) and License are missing while uploading the files.

**Comment by abartov** [comment]
Yeah.  I'm waiting on a patch I submitted to the API client library to fix this properly.

**Comment by abartov** [comment]
This is now done.  I have just released Pronuncify version 0.32, (commit fd1f8d635ca365b70c22ed2c903ee59e4dc4554c) which now uploads to Commons with a full summary and machine-readable license page.

NOTE: it requires an update to the mediawiki_api gem.  Run `gem update mediawiki_api` to ensure you have (at least) version 0.7.1 of the gem.
